image: jhipster/jhipster:v5.0.1

variables:
    CI_PROJECT_DIR: /home/jhipster/app

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - node_modules
        - /home/jhipster/.m2
stages:
    - build
    - test
    - package
    - deploy

before_script:
    - export MAVEN_USER_HOME=/home/jhipster/.m2
    - echo $CI_PROJECT_DIR
    - ls -al $CI_PROJECT_DIR
    - ls -al /home/jhipster/app/
    - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-yarn -DnodeVersion=v8.11.3 -DyarnVersion=v1.6.0 -Dmaven.repo.local=$MAVEN_USER_HOME
    - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dmaven.repo.local=$MAVEN_USER_HOME

maven-build:
    stage: build
    script: ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME

maven-test:
    stage: test
    script:
        - ./mvnw test -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/surefire-reports/*
        # Uncomment following to expire the artifacts after defined period, https://docs.gitlab.com/ee/ci/yaml/README.html#artifacts-expire_in
        # expire_in: 90 day
maven-front-test:
    stage: test
    script:
        - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments=test -Dmaven.repo.local=$MAVEN_USER_HOME
    artifacts:
        paths:
            - target/test-results/jest/*
        # expire_in: 90 day
maven-package:
    stage: package
    script:
        - ./mvnw verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
        - ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.organization=pascalgrimaud-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
    artifacts:
        paths:
            - target/*.war
        # expire_in: 90 day
maven-heroku:
    stage: deploy
    script:
        - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy -DskipTests -Pprod -Dheroku.appName=jhipster-180701 -Dmaven.repo.local=$MAVEN_USER_HOME
