version: '2'
services:
    jhipster180701-app:
        image: jhipster180701
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster180701-postgresql:5432/jhipster180701
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster180701-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster180701-postgresql
